# Generated by Django 3.0.5 on 2020-12-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('pressure_formate', models.BooleanField(default=False)),
                ('vernier_format', models.BooleanField(default=False)),
                ('multimeter_format', models.BooleanField(default=False)),
            ],
        ),
    ]
